name: Daily JEPQ Data Fetch

on:
  schedule:
    - cron: '0 7 * * *'   # Runs every day at 07:00 UTC
  workflow_dispatch:       # Also allows manual trigger from GitHub UI

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # needed for git push

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests openpyxl

    - name: Run script
      run: python script.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add data/*.json
        git diff --quiet && echo "No changes to commit" || git commit -m "Update JEPQ data [skip ci]"
        git push

